volumes:
  ds-db:
    external: false

networks:
  ds-db:
    external: false
  ds-client:
    external: false

services:
  ds-server:
    build: server/
    environment:
      - PORT=8080
      - DB_PASSWORD=user123
      - DB_USER=user
      - DB_NAME=app
      - DB_HOST=ds-db
    networks:
      - ds-db
      - ds-client
    depends_on:
      ds-db:
        condition: service_healthy
  ds-db:
    build: db/
    networks:
      - ds-db
    volumes:
      - ds-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=user123
      - POSTGRES_USER=user
      - POSTGRES_DB=app
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U user -d app']
      interval: 3s
      timeout: 5s
      retries: 5
  ds-client:
    build: client/
    networks:
      - ds-client
    depends_on:
      - ds-server
    stdin_open: true
    tty: true
    environment:
      - SERVER_HOST=ds-server
      - SERVER_PORT=8080
    deploy:
      replicas: 3
