volumes:
  ds-db:
    external: false

networks:
  ds-db:
    external: false

services:
  ds-server:
    build: server/
    ports:
      - '8080:8080'
    environment:
      - DB_PASSWORD=user123
      - DB_USER=user
      - DB_NAME=app
      - DB_HOST=ds-db
    networks:
      - ds-db
    depends_on:
      ds-db:
        condition: service_healthy
  ds-db:
    build: db/
    networks:
      - ds-db
    volumes:
      - ds-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=user123
      - POSTGRES_USER=user
      - POSTGRES_DB=app
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U user -d app']
      interval: 5s
      timeout: 5s
      retries: 5
